# Generated by Django 4.2.2 on 2023-10-26 15:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Personnelles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, null=True, unique=True)),
                ('nom', models.CharField(max_length=25, null=True)),
                ('prenom', models.CharField(max_length=25, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('mot_de_passe', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='circetapp.demande')),
            ],
        ),
        migrations.CreateModel(
            name='Parcours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demande_nom', models.CharField(max_length=255)),
                ('parcours_text', models.TextField()),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='circetapp.personnelles')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('is_text_field', models.BooleanField(default=False)),
                ('demande_suivante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='circetapp.demande')),
                ('next_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_question', to='circetapp.question')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='circetapp.question')),
            ],
        ),
    ]
